/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.equation.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.equation.services.EquationsectionGrammarAccess;

import com.google.inject.Inject;

public class EquationsectionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EquationsectionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openmodelica.modelicaml.editor.xtext.equation.parser.antlr.internal.InternalEquationsectionParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.equation.parser.antlr.internal.InternalEquationsectionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "equation_section";
	}
	
	public EquationsectionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EquationsectionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
