/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.algorithm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlgorithmsectionRuntimeModule extends org.openmodelica.modelicaml.editor.xtext.algorithm.AbstractAlgorithmsectionRuntimeModule {

}
