<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statetransitionguardexpression"
    nsURI="http://www.openmodelica.org/modelicaml/editor/xtext/state/Statetransitionguardexpression"
    nsPrefix="statetransitionguardexpression">
  <eClassifiers xsi:type="ecore:EClass" name="expression" eSuperTypes="../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simple_Expr" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//simple_expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="primary" eSuperTypes="../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//primary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Name_Function" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//name_Function"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Initial_ref" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//initial_ref"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expr" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//ExprDer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mac_A" eType="#//Macro_After"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mac_E" eType="#//Macro_EVENT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mac_C" eType="#//Macro_CHANGE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mac_S" eType="#//Macro_SIGNAL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Else" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro_After">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro_BEFORE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro_SIGNAL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro_EVENT">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro_CHANGE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
