/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.declaration.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.declaration.services.DeclarationGrammarAccess;

import com.google.inject.Inject;

public class DeclarationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DeclarationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openmodelica.modelicaml.editor.xtext.declaration.parser.antlr.internal.InternalDeclarationParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.declaration.parser.antlr.internal.InternalDeclarationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "component_declaration";
	}
	
	public DeclarationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DeclarationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
