<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithmsection"
    nsURI="http://www.openmodelica.org/modelicaml/editor/xtext/algorithm/Algorithmsection"
    nsPrefix="algorithmsection">
  <eClassifiers xsi:type="ecore:EClass" name="algorithm_clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Algorithm" upperBound="-1"
        eType="#//statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="If_statement" eType="#//if_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="State_OutputExprList" eType="#//state_OutputExprList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Algo_M_G" eType="#//Algorithm_Macros_GEN_SIGNAL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state_Comp_Ref" eType="#//state_Comp_Ref"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="For_statement" eType="#//for_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="When_statement" eType="#//when_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="While_statement" eType="#//while_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Algo_G_I" eType="#//Algorithm_Macros_GEN_INC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Algo_G_C" eType="#//Algorithm_Macros_GEN_CHANGE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm_Macros_GEN_SIGNAL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm_Macros_GEN_INC">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm_Macros_GEN_CHANGE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="state_OutputExprList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_expression_list"
        eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//output_expression_list"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_ref" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fun_call_args" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//function_call_args"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="state_Comp_Ref">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component_reference" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//component_reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fun_call_args" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//function_call_args"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="when_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="When_expr" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="When_stat_true" upperBound="-1"
        eType="#//statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Else_When_expr" upperBound="-1"
        eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Then_statement" upperBound="-1"
        eType="#//statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="while_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="while_expr" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="While_stat" upperBound="-1"
        eType="#//statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="for_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="for_loop" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//for_indices"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="For_algo" upperBound="-1"
        eType="#//statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="if_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprtrue" eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprStilltrue" upperBound="-1"
        eType="ecore:EClass ../../../../../../../../org.openmodelica.modelicaml.editor.xtext.modeleditor/model/Modeleditor.ecore#//expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
