/*
* generated by Xtext
*/
package org.modelica.xtext.contentassist;

import org.modelica.xtext.contentassist.AbstractModelicaASTProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ModelicaASTProposalProvider extends AbstractModelicaASTProposalProvider {

}
