/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.activity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ActivitycontrolflowguardexpressionUiModule extends org.openmodelica.modelicaml.editor.xtext.activity.ui.AbstractActivitycontrolflowguardexpressionUiModule {
	public ActivitycontrolflowguardexpressionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
