/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.array.ui.contentassist;

import org.openmodelica.modelicaml.editor.xtext.array.ui.contentassist.AbstractArraysubscriptProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ArraysubscriptProposalProvider extends AbstractArraysubscriptProposalProvider {

}
