/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.equation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EquationsectionRuntimeModule extends org.openmodelica.modelicaml.editor.xtext.equation.AbstractEquationsectionRuntimeModule {

}
