/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.equation.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EquationsectionProposalProvider extends AbstractEquationsectionProposalProvider {

}
