/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.valuebinding.scoping;

import org.openmodelica.modelicaml.editor.xtext.model.scoping.ModeleditorScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ProviderScopeProvider extends ModeleditorScopeProvider {

}
