/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.declaration.ui.contentassist;

import org.openmodelica.modelicaml.editor.xtext.declaration.ui.contentassist.AbstractDeclarationProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DeclarationProposalProvider extends AbstractDeclarationProposalProvider {

}
