/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.state.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatetransitionguardexpressionUiModule extends org.openmodelica.modelicaml.editor.xtext.state.ui.AbstractStatetransitionguardexpressionUiModule {
	public StatetransitionguardexpressionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
