/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.algorithm.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AlgorithmsectionProposalProvider extends AbstractAlgorithmsectionProposalProvider {

}
