/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.condition.ui.contentassist;

import org.openmodelica.modelicaml.editor.xtext.condition.ui.contentassist.AbstractConditionalattributeProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ConditionalattributeProposalProvider extends AbstractConditionalattributeProposalProvider {

}
