/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.condition.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.condition.services.ConditionalattributeGrammarAccess;

import com.google.inject.Inject;

public class ConditionalattributeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ConditionalattributeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openmodelica.modelicaml.editor.xtext.condition.parser.antlr.internal.InternalConditionalattributeParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.condition.parser.antlr.internal.InternalConditionalattributeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "conditional_attribute";
	}
	
	public ConditionalattributeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ConditionalattributeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
