/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.array.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.array.services.ArraysubscriptGrammarAccess;

import com.google.inject.Inject;

public class ArraysubscriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ArraysubscriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openmodelica.modelicaml.editor.xtext.array.parser.antlr.internal.InternalArraysubscriptParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.array.parser.antlr.internal.InternalArraysubscriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "subscript";
	}
	
	public ArraysubscriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ArraysubscriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
