/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.array.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ArraysubscriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/openmodelica/modelicaml/editor/xtext/array/parser/antlr/internal/InternalArraysubscript.tokens");
	}
}
