/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.valuebinding.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ClientAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/openmodelica/modelicaml/editor/xtext/valuebinding/parser/antlr/internal/InternalClient.tokens");
	}
}
