/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.valuebinding.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.valuebinding.services.ClientGrammarAccess;

import com.google.inject.Inject;

public class ClientParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ClientGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openmodelica.modelicaml.editor.xtext.valuebinding.parser.antlr.internal.InternalClientParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.valuebinding.parser.antlr.internal.InternalClientParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ClientOperation";
	}
	
	public ClientGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ClientGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
