/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.valuebinding;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProviderRuntimeModule extends org.openmodelica.modelicaml.editor.xtext.valuebinding.AbstractProviderRuntimeModule {

}
