/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.array;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArraysubscriptRuntimeModule extends org.openmodelica.modelicaml.editor.xtext.array.AbstractArraysubscriptRuntimeModule {

}
