/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.modification.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ModificationTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
