
/*
 * generated by Xtext
 */
 
package org.openmodelica.modelicaml.editor.xtext.valuebinding.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class ProviderExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.openmodelica.modelicaml.editor.xtext.valuebinding.ui.internal.ProviderActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.openmodelica.modelicaml.editor.xtext.valuebinding.ui.internal.ProviderActivator.getInstance().getInjector("org.openmodelica.modelicaml.editor.xtext.valuebinding.Provider");
	}
	
}
