package org.modelica.mdt.corba;

/**
* ModeqCommunication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from modeq_communication.idl
* den 7 oktober 2005 kl 11:49 CEST
*/


// As simple as can be modeq communication, sending and recieving of strings.
public interface ModeqCommunication extends ModeqCommunicationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ModeqCommunication
