/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.declaration.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DeclarationUiModule extends org.openmodelica.modelicaml.editor.xtext.declaration.ui.AbstractDeclarationUiModule {
	public DeclarationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
