/*
* generated by Xtext
*/
package org.modelica.xtext.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.modelica.xtext.services.ModelicaBaseGrammarAccess;

public class ModelicaBaseParser extends AbstractContentAssistParser {
	
	@Inject
	private ModelicaBaseGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseLexer createLexer(CharStream stream) {
		return new org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseLexer(stream);
	}
	
	@Override
	protected org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseParser createParser() {
		org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseParser result = new org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				{
					put(grammarAccess.getEntityDefinitionAccess().getAlternatives(), "rule__EntityDefinition__Alternatives");
					put(grammarAccess.getClassDefinitionAccess().getAlternatives_4(), "rule__ClassDefinition__Alternatives_4");
					put(grammarAccess.getClassDefinitionAccess().getAlternatives_6(), "rule__ClassDefinition__Alternatives_6");
					put(grammarAccess.getEnumerationAccess().getAlternatives_5(), "rule__Enumeration__Alternatives_5");
					put(grammarAccess.getElementListAccess().getAlternatives_0(), "rule__ElementList__Alternatives_0");
					put(grammarAccess.getElementList2Access().getAlternatives(), "rule__ElementList2__Alternatives");
					put(grammarAccess.getElementList2Access().getAlternatives_0_2_0(), "rule__ElementList2__Alternatives_0_2_0");
					put(grammarAccess.getElementList2Access().getAlternatives_1_2_0(), "rule__ElementList2__Alternatives_1_2_0");
					put(grammarAccess.getClassElementAccess().getAlternatives(), "rule__ClassElement__Alternatives");
					put(grammarAccess.getClassElementAccess().getAlternatives_2_4(), "rule__ClassElement__Alternatives_2_4");
					put(grammarAccess.getClassElementAccess().getAlternatives_2_4_0(), "rule__ClassElement__Alternatives_2_4_0");
					put(grammarAccess.getReplaceableElementClauseAccess().getEntityAlternatives_1_0(), "rule__ReplaceableElementClause__EntityAlternatives_1_0");
					put(grammarAccess.getImport_clauseAccess().getAlternatives_1(), "rule__Import_clause__Alternatives_1");
					put(grammarAccess.getConstraining_clauseAccess().getAlternatives_0(), "rule__Constraining_clause__Alternatives_0");
					put(grammarAccess.getType_prefixAccess().getAlternatives_0(), "rule__Type_prefix__Alternatives_0");
					put(grammarAccess.getType_prefixAccess().getAlternatives_1(), "rule__Type_prefix__Alternatives_1");
					put(grammarAccess.getType_prefixAccess().getAlternatives_2(), "rule__Type_prefix__Alternatives_2");
					put(grammarAccess.getModificationAccess().getAlternatives(), "rule__Modification__Alternatives");
					put(grammarAccess.getSimpleModificationAccess().getAlternatives(), "rule__SimpleModification__Alternatives");
					put(grammarAccess.getArgumentAccess().getAlternatives(), "rule__Argument__Alternatives");
					put(grammarAccess.getArgumentAccess().getAlternatives_0_2(), "rule__Argument__Alternatives_0_2");
					put(grammarAccess.getElementRedeclarationAccess().getAlternatives_3(), "rule__ElementRedeclaration__Alternatives_3");
					put(grammarAccess.getElementRedeclarationAccess().getAlternatives_3_0(), "rule__ElementRedeclaration__Alternatives_3_0");
					put(grammarAccess.getElementReplaceableClauseAccess().getElementAlternatives_1_0(), "rule__ElementReplaceableClause__ElementAlternatives_1_0");
					put(grammarAccess.getEquation_rule_clauseAccess().getAlternatives_1(), "rule__Equation_rule_clause__Alternatives_1");
					put(grammarAccess.getAlgorithm_clauseAccess().getAlternatives_1(), "rule__Algorithm_clause__Alternatives_1");
					put(grammarAccess.getEquation_ruleAccess().getAlternatives_0(), "rule__Equation_rule__Alternatives_0");
					put(grammarAccess.getAlgorithmAccess().getAlternatives_0(), "rule__Algorithm__Alternatives_0");
					put(grammarAccess.getAssign_clause_aAccess().getAlternatives_1(), "rule__Assign_clause_a__Alternatives_1");
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getExpression_or_emptyAccess().getAlternatives(), "rule__Expression_or_empty__Alternatives");
					put(grammarAccess.getRelationAccess().getAlternatives_1_0(), "rule__Relation__Alternatives_1_0");
					put(grammarAccess.getArithmetic_expressionAccess().getAlternatives_1_0(), "rule__Arithmetic_expression__Alternatives_1_0");
					put(grammarAccess.getUnary_arithmetic_expressionAccess().getAlternatives(), "rule__Unary_arithmetic_expression__Alternatives");
					put(grammarAccess.getTermAccess().getAlternatives_1_0(), "rule__Term__Alternatives_1_0");
					put(grammarAccess.getFactorAccess().getAlternatives_1_0(), "rule__Factor__Alternatives_1_0");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getComponent_reference__function_callAccess().getAlternatives(), "rule__Component_reference__function_call__Alternatives");
					put(grammarAccess.getName_pathAccess().getAlternatives(), "rule__Name_path__Alternatives");
					put(grammarAccess.getName_path_starAccess().getAlternatives(), "rule__Name_path_star__Alternatives");
					put(grammarAccess.getFor_or_expression_listAccess().getAlternatives_1(), "rule__For_or_expression_list__Alternatives_1");
					put(grammarAccess.getSubscriptAccess().getAlternatives(), "rule__Subscript__Alternatives");
					put(grammarAccess.getClassTypeAccess().getAlternatives(), "rule__ClassType__Alternatives");
					put(grammarAccess.getStorageUnitAccess().getGroup(), "rule__StorageUnit__Group__0");
					put(grammarAccess.getStorageUnitAccess().getGroup_0(), "rule__StorageUnit__Group_0__0");
					put(grammarAccess.getStorageUnitAccess().getGroup_1(), "rule__StorageUnit__Group_1__0");
					put(grammarAccess.getClassDefinitionAccess().getGroup(), "rule__ClassDefinition__Group__0");
					put(grammarAccess.getClassDefinitionAccess().getGroup_4_0(), "rule__ClassDefinition__Group_4_0__0");
					put(grammarAccess.getClassDefinitionAccess().getGroup_4_1(), "rule__ClassDefinition__Group_4_1__0");
					put(grammarAccess.getPartialDerivativeAccess().getGroup(), "rule__PartialDerivative__Group__0");
					put(grammarAccess.getClassModificationAccess().getGroup(), "rule__ClassModification__Group__0");
					put(grammarAccess.getClassOverloadingAccess().getGroup(), "rule__ClassOverloading__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup(), "rule__Enumeration__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup_5_0(), "rule__Enumeration__Group_5_0__0");
					put(grammarAccess.getEnumerationAccess().getGroup_5_0_2(), "rule__Enumeration__Group_5_0_2__0");
					put(grammarAccess.getIdent_listAccess().getGroup(), "rule__Ident_list__Group__0");
					put(grammarAccess.getIdent_listAccess().getGroup_1(), "rule__Ident_list__Group_1__0");
					put(grammarAccess.getName_listAccess().getGroup(), "rule__Name_list__Group__0");
					put(grammarAccess.getName_listAccess().getGroup_1(), "rule__Name_list__Group_1__0");
					put(grammarAccess.getExternal_clauseAccess().getGroup(), "rule__External_clause__Group__0");
					put(grammarAccess.getExternal_clauseAccess().getGroup_5(), "rule__External_clause__Group_5__0");
					put(grammarAccess.getExternal_function_callAccess().getGroup(), "rule__External_function_call__Group__0");
					put(grammarAccess.getExternal_function_callAccess().getGroup_0(), "rule__External_function_call__Group_0__0");
					put(grammarAccess.getElementListAccess().getGroup(), "rule__ElementList__Group__0");
					put(grammarAccess.getElementList2Access().getGroup_0(), "rule__ElementList2__Group_0__0");
					put(grammarAccess.getElementList2Access().getGroup_0_2(), "rule__ElementList2__Group_0_2__0");
					put(grammarAccess.getElementList2Access().getGroup_1(), "rule__ElementList2__Group_1__0");
					put(grammarAccess.getElementList2Access().getGroup_1_2(), "rule__ElementList2__Group_1_2__0");
					put(grammarAccess.getClassElementAccess().getGroup_2(), "rule__ClassElement__Group_2__0");
					put(grammarAccess.getReplaceableElementClauseAccess().getGroup(), "rule__ReplaceableElementClause__Group__0");
					put(grammarAccess.getImport_clauseAccess().getGroup(), "rule__Import_clause__Group__0");
					put(grammarAccess.getImport_clauseAccess().getGroup_1_0(), "rule__Import_clause__Group_1_0__0");
					put(grammarAccess.getExtends_clauseAccess().getGroup(), "rule__Extends_clause__Group__0");
					put(grammarAccess.getConstraining_clauseAccess().getGroup(), "rule__Constraining_clause__Group__0");
					put(grammarAccess.getConstraining_clauseAccess().getGroup_0_0(), "rule__Constraining_clause__Group_0_0__0");
					put(grammarAccess.getConstraining_clauseAccess().getGroup_0_1(), "rule__Constraining_clause__Group_0_1__0");
					put(grammarAccess.getComponent_clauseAccess().getGroup(), "rule__Component_clause__Group__0");
					put(grammarAccess.getComponent_clauseAccess().getGroup_3(), "rule__Component_clause__Group_3__0");
					put(grammarAccess.getType_prefixAccess().getGroup(), "rule__Type_prefix__Group__0");
					put(grammarAccess.getType_specifierAccess().getGroup(), "rule__Type_specifier__Group__0");
					put(grammarAccess.getComponent_declarationAccess().getGroup(), "rule__Component_declaration__Group__0");
					put(grammarAccess.getComponent_declarationAccess().getGroup_3(), "rule__Component_declaration__Group_3__0");
					put(grammarAccess.getSimpleModificationAccess().getGroup_0(), "rule__SimpleModification__Group_0__0");
					put(grammarAccess.getSimpleModificationAccess().getGroup_1(), "rule__SimpleModification__Group_1__0");
					put(grammarAccess.getClass_modificationAccess().getGroup(), "rule__Class_modification__Group__0");
					put(grammarAccess.getClass_modificationAccess().getGroup_1(), "rule__Class_modification__Group_1__0");
					put(grammarAccess.getClass_modificationAccess().getGroup_1_1(), "rule__Class_modification__Group_1_1__0");
					put(grammarAccess.getClass_modificationAccess().getGroup_3(), "rule__Class_modification__Group_3__0");
					put(grammarAccess.getArgumentAccess().getGroup_0(), "rule__Argument__Group_0__0");
					put(grammarAccess.getElementModificationAccess().getGroup(), "rule__ElementModification__Group__0");
					put(grammarAccess.getElementRedeclarationAccess().getGroup(), "rule__ElementRedeclaration__Group__0");
					put(grammarAccess.getElementReplaceableClauseAccess().getGroup(), "rule__ElementReplaceableClause__Group__0");
					put(grammarAccess.getElementComponentClauseAccess().getGroup(), "rule__ElementComponentClause__Group__0");
					put(grammarAccess.getEquation_rule_clauseAccess().getGroup(), "rule__Equation_rule_clause__Group__0");
					put(grammarAccess.getEquation_rule_clauseAccess().getGroup_1_0(), "rule__Equation_rule_clause__Group_1_0__0");
					put(grammarAccess.getEquation_rule_clauseAccess().getGroup_1_1(), "rule__Equation_rule_clause__Group_1_1__0");
					put(grammarAccess.getAlgorithm_clauseAccess().getGroup(), "rule__Algorithm_clause__Group__0");
					put(grammarAccess.getAlgorithm_clauseAccess().getGroup_1_0(), "rule__Algorithm_clause__Group_1_0__0");
					put(grammarAccess.getAlgorithm_clauseAccess().getGroup_1_1(), "rule__Algorithm_clause__Group_1_1__0");
					put(grammarAccess.getInitial_equation_rule_clauseAccess().getGroup(), "rule__Initial_equation_rule_clause__Group__0");
					put(grammarAccess.getInitial_algorithm_clauseAccess().getGroup(), "rule__Initial_algorithm_clause__Group__0");
					put(grammarAccess.getEquation_ruleAccess().getGroup(), "rule__Equation_rule__Group__0");
					put(grammarAccess.getAlgorithmAccess().getGroup(), "rule__Algorithm__Group__0");
					put(grammarAccess.getAssign_clause_aAccess().getGroup(), "rule__Assign_clause_a__Group__0");
					put(grammarAccess.getAssign_clause_aAccess().getGroup_1_0(), "rule__Assign_clause_a__Group_1_0__0");
					put(grammarAccess.getAssign_clause_aAccess().getGroup_1_1(), "rule__Assign_clause_a__Group_1_1__0");
					put(grammarAccess.getEquality_equation_ruleAccess().getGroup(), "rule__Equality_equation_rule__Group__0");
					put(grammarAccess.getEquality_equation_ruleAccess().getGroup_1(), "rule__Equality_equation_rule__Group_1__0");
					put(grammarAccess.getConditional_equation_rule_eAccess().getGroup(), "rule__Conditional_equation_rule_e__Group__0");
					put(grammarAccess.getConditional_equation_rule_eAccess().getGroup_3(), "rule__Conditional_equation_rule_e__Group_3__0");
					put(grammarAccess.getConditional_equation_rule_eAccess().getGroup_5(), "rule__Conditional_equation_rule_e__Group_5__0");
					put(grammarAccess.getConditional_equation_rule_eAccess().getGroup_5_1(), "rule__Conditional_equation_rule_e__Group_5_1__0");
					put(grammarAccess.getConditional_equation_rule_aAccess().getGroup(), "rule__Conditional_equation_rule_a__Group__0");
					put(grammarAccess.getConditional_equation_rule_aAccess().getGroup_3(), "rule__Conditional_equation_rule_a__Group_3__0");
					put(grammarAccess.getConditional_equation_rule_aAccess().getGroup_5(), "rule__Conditional_equation_rule_a__Group_5__0");
					put(grammarAccess.getConditional_equation_rule_aAccess().getGroup_5_1(), "rule__Conditional_equation_rule_a__Group_5_1__0");
					put(grammarAccess.getFor_clause_eAccess().getGroup(), "rule__For_clause_e__Group__0");
					put(grammarAccess.getFor_clause_eAccess().getGroup_3(), "rule__For_clause_e__Group_3__0");
					put(grammarAccess.getFor_clause_aAccess().getGroup(), "rule__For_clause_a__Group__0");
					put(grammarAccess.getFor_clause_aAccess().getGroup_3(), "rule__For_clause_a__Group_3__0");
					put(grammarAccess.getWhile_clauseAccess().getGroup(), "rule__While_clause__Group__0");
					put(grammarAccess.getWhile_clauseAccess().getGroup_3(), "rule__While_clause__Group_3__0");
					put(grammarAccess.getWhen_clause_eAccess().getGroup(), "rule__When_clause_e__Group__0");
					put(grammarAccess.getWhen_clause_eAccess().getGroup_3(), "rule__When_clause_e__Group_3__0");
					put(grammarAccess.getElse_when_eAccess().getGroup(), "rule__Else_when_e__Group__0");
					put(grammarAccess.getElse_when_eAccess().getGroup_3(), "rule__Else_when_e__Group_3__0");
					put(grammarAccess.getWhen_clause_aAccess().getGroup(), "rule__When_clause_a__Group__0");
					put(grammarAccess.getWhen_clause_aAccess().getGroup_3(), "rule__When_clause_a__Group_3__0");
					put(grammarAccess.getElse_when_aAccess().getGroup(), "rule__Else_when_a__Group__0");
					put(grammarAccess.getElse_when_aAccess().getGroup_3(), "rule__Else_when_a__Group_3__0");
					put(grammarAccess.getEquation_rule_elseifAccess().getGroup(), "rule__Equation_rule_elseif__Group__0");
					put(grammarAccess.getEquation_rule_elseifAccess().getGroup_3(), "rule__Equation_rule_elseif__Group_3__0");
					put(grammarAccess.getAlgorithm_elseifAccess().getGroup(), "rule__Algorithm_elseif__Group__0");
					put(grammarAccess.getAlgorithm_elseifAccess().getGroup_3(), "rule__Algorithm_elseif__Group_3__0");
					put(grammarAccess.getConnect_clauseAccess().getGroup(), "rule__Connect_clause__Group__0");
					put(grammarAccess.getConnector_refAccess().getGroup(), "rule__Connector_ref__Group__0");
					put(grammarAccess.getConnector_refAccess().getGroup_2(), "rule__Connector_ref__Group_2__0");
					put(grammarAccess.getConnector_ref_2Access().getGroup(), "rule__Connector_ref_2__Group__0");
					put(grammarAccess.getExpression_or_emptyAccess().getGroup_1(), "rule__Expression_or_empty__Group_1__0");
					put(grammarAccess.getIf_expressionAccess().getGroup(), "rule__If_expression__Group__0");
					put(grammarAccess.getElseif_expressionAccess().getGroup(), "rule__Elseif_expression__Group__0");
					put(grammarAccess.getFor_indicesAccess().getGroup(), "rule__For_indices__Group__0");
					put(grammarAccess.getFor_indicesAccess().getGroup_1(), "rule__For_indices__Group_1__0");
					put(grammarAccess.getFor_indexAccess().getGroup(), "rule__For_index__Group__0");
					put(grammarAccess.getFor_indexAccess().getGroup_1(), "rule__For_index__Group_1__0");
					put(grammarAccess.getSimple_exprAccess().getGroup(), "rule__Simple_expr__Group__0");
					put(grammarAccess.getSimple_exprAccess().getGroup_1(), "rule__Simple_expr__Group_1__0");
					put(grammarAccess.getSimple_exprAccess().getGroup_1_2(), "rule__Simple_expr__Group_1_2__0");
					put(grammarAccess.getLogical_expressionAccess().getGroup(), "rule__Logical_expression__Group__0");
					put(grammarAccess.getLogical_expressionAccess().getGroup_1(), "rule__Logical_expression__Group_1__0");
					put(grammarAccess.getLogical_termAccess().getGroup(), "rule__Logical_term__Group__0");
					put(grammarAccess.getLogical_termAccess().getGroup_1(), "rule__Logical_term__Group_1__0");
					put(grammarAccess.getLogical_factorAccess().getGroup(), "rule__Logical_factor__Group__0");
					put(grammarAccess.getRelationAccess().getGroup(), "rule__Relation__Group__0");
					put(grammarAccess.getRelationAccess().getGroup_1(), "rule__Relation__Group_1__0");
					put(grammarAccess.getArithmetic_expressionAccess().getGroup(), "rule__Arithmetic_expression__Group__0");
					put(grammarAccess.getArithmetic_expressionAccess().getGroup_1(), "rule__Arithmetic_expression__Group_1__0");
					put(grammarAccess.getUnary_arithmetic_expressionAccess().getGroup_0(), "rule__Unary_arithmetic_expression__Group_0__0");
					put(grammarAccess.getUnary_arithmetic_expressionAccess().getGroup_1(), "rule__Unary_arithmetic_expression__Group_1__0");
					put(grammarAccess.getUnary_arithmetic_expressionAccess().getGroup_2(), "rule__Unary_arithmetic_expression__Group_2__0");
					put(grammarAccess.getUnary_arithmetic_expressionAccess().getGroup_3(), "rule__Unary_arithmetic_expression__Group_3__0");
					put(grammarAccess.getTermAccess().getGroup(), "rule__Term__Group__0");
					put(grammarAccess.getTermAccess().getGroup_1(), "rule__Term__Group_1__0");
					put(grammarAccess.getFactorAccess().getGroup(), "rule__Factor__Group__0");
					put(grammarAccess.getFactorAccess().getGroup_1(), "rule__Factor__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_6(), "rule__Primary__Group_6__0");
					put(grammarAccess.getPrimaryAccess().getGroup_7(), "rule__Primary__Group_7__0");
					put(grammarAccess.getPrimaryAccess().getGroup_8(), "rule__Primary__Group_8__0");
					put(grammarAccess.getPrimaryAccess().getGroup_8_2(), "rule__Primary__Group_8_2__0");
					put(grammarAccess.getPrimaryAccess().getGroup_9(), "rule__Primary__Group_9__0");
					put(grammarAccess.getComponent_reference__function_callAccess().getGroup_0(), "rule__Component_reference__function_call__Group_0__0");
					put(grammarAccess.getComponent_reference__function_callAccess().getGroup_1(), "rule__Component_reference__function_call__Group_1__0");
					put(grammarAccess.getName_pathAccess().getGroup_1(), "rule__Name_path__Group_1__0");
					put(grammarAccess.getName_path_starAccess().getGroup_0(), "rule__Name_path_star__Group_0__0");
					put(grammarAccess.getName_path_starAccess().getGroup_1(), "rule__Name_path_star__Group_1__0");
					put(grammarAccess.getComponent_referenceAccess().getGroup(), "rule__Component_reference__Group__0");
					put(grammarAccess.getComponent_referenceAccess().getGroup_2(), "rule__Component_reference__Group_2__0");
					put(grammarAccess.getFunction_callAccess().getGroup(), "rule__Function_call__Group__0");
					put(grammarAccess.getFunction_argumentsAccess().getGroup(), "rule__Function_arguments__Group__0");
					put(grammarAccess.getFor_or_expression_listAccess().getGroup(), "rule__For_or_expression_list__Group__0");
					put(grammarAccess.getFor_or_expression_listAccess().getGroup_1_0(), "rule__For_or_expression_list__Group_1_0__0");
					put(grammarAccess.getFor_or_expression_listAccess().getGroup_1_1(), "rule__For_or_expression_list__Group_1_1__0");
					put(grammarAccess.getFor_or_expression_list2Access().getGroup(), "rule__For_or_expression_list2__Group__0");
					put(grammarAccess.getFor_or_expression_list2Access().getGroup_1(), "rule__For_or_expression_list2__Group_1__0");
					put(grammarAccess.getNamed_arguments2Access().getGroup(), "rule__Named_arguments2__Group__0");
					put(grammarAccess.getNamed_arguments2Access().getGroup_1(), "rule__Named_arguments2__Group_1__0");
					put(grammarAccess.getNamed_argumentAccess().getGroup(), "rule__Named_argument__Group__0");
					put(grammarAccess.getExpression_list2Access().getGroup(), "rule__Expression_list2__Group__0");
					put(grammarAccess.getExpression_list2Access().getGroup_1(), "rule__Expression_list2__Group_1__0");
					put(grammarAccess.getArray_subscriptsAccess().getGroup(), "rule__Array_subscripts__Group__0");
					put(grammarAccess.getArray_subscriptsAccess().getGroup_2(), "rule__Array_subscripts__Group_2__0");
					put(grammarAccess.getCommentAccess().getGroup(), "rule__Comment__Group__0");
					put(grammarAccess.getString_commentAccess().getGroup(), "rule__String_comment__Group__0");
					put(grammarAccess.getString_commentAccess().getGroup_1(), "rule__String_comment__Group_1__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getStorageUnitAccess().getClassDefinitionAssignment_1_1(), "rule__StorageUnit__ClassDefinitionAssignment_1_1");
					put(grammarAccess.getClassDefinitionAccess().getEncapsulatedAssignment_0(), "rule__ClassDefinition__EncapsulatedAssignment_0");
					put(grammarAccess.getClassDefinitionAccess().getPartialAssignment_1(), "rule__ClassDefinition__PartialAssignment_1");
					put(grammarAccess.getClassDefinitionAccess().getExpandableAssignment_2(), "rule__ClassDefinition__ExpandableAssignment_2");
					put(grammarAccess.getClassDefinitionAccess().getClassTypeAssignment_3(), "rule__ClassDefinition__ClassTypeAssignment_3");
					put(grammarAccess.getClassDefinitionAccess().getNameAssignment_4_0_0(), "rule__ClassDefinition__NameAssignment_4_0_0");
					put(grammarAccess.getClassDefinitionAccess().getCommentAssignment_4_0_1(), "rule__ClassDefinition__CommentAssignment_4_0_1");
					put(grammarAccess.getClassDefinitionAccess().getModificationAssignment_4_1_2(), "rule__ClassDefinition__ModificationAssignment_4_1_2");
					put(grammarAccess.getClassDefinitionAccess().getElemListAssignment_5(), "rule__ClassDefinition__ElemListAssignment_5");
					put(grammarAccess.getClassDefinitionAccess().getElemListAssignment_6_0(), "rule__ClassDefinition__ElemListAssignment_6_0");
					put(grammarAccess.getClassDefinitionAccess().getInitialEquationClausesAssignment_6_1(), "rule__ClassDefinition__InitialEquationClausesAssignment_6_1");
					put(grammarAccess.getClassDefinitionAccess().getInitialAlgorithmClausesAssignment_6_2(), "rule__ClassDefinition__InitialAlgorithmClausesAssignment_6_2");
					put(grammarAccess.getClassDefinitionAccess().getEquationClausesAssignment_6_3(), "rule__ClassDefinition__EquationClausesAssignment_6_3");
					put(grammarAccess.getClassDefinitionAccess().getAlgorithmClausesAssignment_6_4(), "rule__ClassDefinition__AlgorithmClausesAssignment_6_4");
					put(grammarAccess.getClassDefinitionAccess().getExtClauseAssignment_7(), "rule__ClassDefinition__ExtClauseAssignment_7");
					put(grammarAccess.getPartialDerivativeAccess().getNameAssignment_1(), "rule__PartialDerivative__NameAssignment_1");
					put(grammarAccess.getPartialDerivativeAccess().getCommentAssignment_9(), "rule__PartialDerivative__CommentAssignment_9");
					put(grammarAccess.getClassModificationAccess().getClassTypeAssignment_0(), "rule__ClassModification__ClassTypeAssignment_0");
					put(grammarAccess.getClassModificationAccess().getNameAssignment_1(), "rule__ClassModification__NameAssignment_1");
					put(grammarAccess.getClassModificationAccess().getTypeSpecifierAssignment_4(), "rule__ClassModification__TypeSpecifierAssignment_4");
					put(grammarAccess.getClassModificationAccess().getModificationAssignment_5(), "rule__ClassModification__ModificationAssignment_5");
					put(grammarAccess.getClassModificationAccess().getCommentAssignment_6(), "rule__ClassModification__CommentAssignment_6");
					put(grammarAccess.getClassOverloadingAccess().getClassTypeAssignment_0(), "rule__ClassOverloading__ClassTypeAssignment_0");
					put(grammarAccess.getClassOverloadingAccess().getNameAssignment_1(), "rule__ClassOverloading__NameAssignment_1");
					put(grammarAccess.getClassOverloadingAccess().getCommentAssignment_7(), "rule__ClassOverloading__CommentAssignment_7");
					put(grammarAccess.getEnumerationAccess().getClassTypeAssignment_0(), "rule__Enumeration__ClassTypeAssignment_0");
					put(grammarAccess.getEnumerationAccess().getNameAssignment_1(), "rule__Enumeration__NameAssignment_1");
					put(grammarAccess.getEnumerationAccess().getIdentAssignment_5_0_0(), "rule__Enumeration__IdentAssignment_5_0_0");
					put(grammarAccess.getEnumerationAccess().getEnumCommentsAssignment_5_0_1(), "rule__Enumeration__EnumCommentsAssignment_5_0_1");
					put(grammarAccess.getEnumerationAccess().getIdentAssignment_5_0_2_1(), "rule__Enumeration__IdentAssignment_5_0_2_1");
					put(grammarAccess.getEnumerationAccess().getEnumCommentsAssignment_5_0_2_2(), "rule__Enumeration__EnumCommentsAssignment_5_0_2_2");
					put(grammarAccess.getEnumerationAccess().getCommentAssignment_7(), "rule__Enumeration__CommentAssignment_7");
					put(grammarAccess.getExternal_clauseAccess().getLanguageSpecificationAssignment_1(), "rule__External_clause__LanguageSpecificationAssignment_1");
					put(grammarAccess.getExternal_clauseAccess().getAnnotationAssignment_3(), "rule__External_clause__AnnotationAssignment_3");
					put(grammarAccess.getExternal_clauseAccess().getExtAnnotationAssignment_5_0(), "rule__External_clause__ExtAnnotationAssignment_5_0");
					put(grammarAccess.getElementListAccess().getElementsAssignment_0_0(), "rule__ElementList__ElementsAssignment_0_0");
					put(grammarAccess.getElementListAccess().getAnnotationsAssignment_0_1(), "rule__ElementList__AnnotationsAssignment_0_1");
					put(grammarAccess.getElementList2Access().getElementsAssignment_0_2_0_0(), "rule__ElementList2__ElementsAssignment_0_2_0_0");
					put(grammarAccess.getElementList2Access().getAnnotationsAssignment_0_2_0_1(), "rule__ElementList2__AnnotationsAssignment_0_2_0_1");
					put(grammarAccess.getElementList2Access().getElementsAssignment_1_2_0_0(), "rule__ElementList2__ElementsAssignment_1_2_0_0");
					put(grammarAccess.getElementList2Access().getAnnotationsAssignment_1_2_0_1(), "rule__ElementList2__AnnotationsAssignment_1_2_0_1");
					put(grammarAccess.getReplaceableElementClauseAccess().getEntityAssignment_1(), "rule__ReplaceableElementClause__EntityAssignment_1");
					put(grammarAccess.getReplaceableElementClauseAccess().getConstrainAssignment_2(), "rule__ReplaceableElementClause__ConstrainAssignment_2");
					put(grammarAccess.getImport_clauseAccess().getAsNameAssignment_1_0_0(), "rule__Import_clause__AsNameAssignment_1_0_0");
					put(grammarAccess.getImport_clauseAccess().getNameAssignment_1_0_2(), "rule__Import_clause__NameAssignment_1_0_2");
					put(grammarAccess.getImport_clauseAccess().getNameAssignment_1_1(), "rule__Import_clause__NameAssignment_1_1");
					put(grammarAccess.getImport_clauseAccess().getCommentAssignment_2(), "rule__Import_clause__CommentAssignment_2");
					put(grammarAccess.getExtends_clauseAccess().getBaseClassAssignment_1(), "rule__Extends_clause__BaseClassAssignment_1");
					put(grammarAccess.getExtends_clauseAccess().getModificationAssignment_2(), "rule__Extends_clause__ModificationAssignment_2");
					put(grammarAccess.getExtends_clauseAccess().getAnnotationAssignment_3(), "rule__Extends_clause__AnnotationAssignment_3");
					put(grammarAccess.getConstraining_clauseAccess().getNameAssignment_0_0_1(), "rule__Constraining_clause__NameAssignment_0_0_1");
					put(grammarAccess.getConstraining_clauseAccess().getModificationAssignment_0_0_2(), "rule__Constraining_clause__ModificationAssignment_0_0_2");
					put(grammarAccess.getConstraining_clauseAccess().getNameAssignment_0_1_1(), "rule__Constraining_clause__NameAssignment_0_1_1");
					put(grammarAccess.getConstraining_clauseAccess().getModificationAssignment_0_1_2(), "rule__Constraining_clause__ModificationAssignment_0_1_2");
					put(grammarAccess.getConstraining_clauseAccess().getCommentAssignment_1(), "rule__Constraining_clause__CommentAssignment_1");
					put(grammarAccess.getComponent_clauseAccess().getTypePrefixAssignment_0(), "rule__Component_clause__TypePrefixAssignment_0");
					put(grammarAccess.getComponent_clauseAccess().getTypeSpecifierAssignment_1(), "rule__Component_clause__TypeSpecifierAssignment_1");
					put(grammarAccess.getComponent_clauseAccess().getDeclarationsAssignment_2(), "rule__Component_clause__DeclarationsAssignment_2");
					put(grammarAccess.getComponent_clauseAccess().getDeclarationsAssignment_3_1(), "rule__Component_clause__DeclarationsAssignment_3_1");
					put(grammarAccess.getType_specifierAccess().getNameAssignment_0(), "rule__Type_specifier__NameAssignment_0");
					put(grammarAccess.getType_specifierAccess().getSubscriptsAssignment_1(), "rule__Type_specifier__SubscriptsAssignment_1");
					put(grammarAccess.getComponent_declarationAccess().getSubscriptsAssignment_1(), "rule__Component_declaration__SubscriptsAssignment_1");
					put(grammarAccess.getComponent_declarationAccess().getModificationAssignment_2(), "rule__Component_declaration__ModificationAssignment_2");
					put(grammarAccess.getComponent_declarationAccess().getConditionAssignment_3_1(), "rule__Component_declaration__ConditionAssignment_3_1");
					put(grammarAccess.getComponent_declarationAccess().getCommentAssignment_4(), "rule__Component_declaration__CommentAssignment_4");
					put(grammarAccess.getSimpleModificationAccess().getExpressionAssignment_0_1(), "rule__SimpleModification__ExpressionAssignment_0_1");
					put(grammarAccess.getSimpleModificationAccess().getExpressionAssignment_1_1(), "rule__SimpleModification__ExpressionAssignment_1_1");
					put(grammarAccess.getClass_modificationAccess().getArgumentsAssignment_1_0(), "rule__Class_modification__ArgumentsAssignment_1_0");
					put(grammarAccess.getClass_modificationAccess().getArgumentsAssignment_1_1_1(), "rule__Class_modification__ArgumentsAssignment_1_1_1");
					put(grammarAccess.getClass_modificationAccess().getExpressionAssignment_3_1(), "rule__Class_modification__ExpressionAssignment_3_1");
					put(grammarAccess.getElementModificationAccess().getComponetRefAssignment_0(), "rule__ElementModification__ComponetRefAssignment_0");
					put(grammarAccess.getElementModificationAccess().getModificationAssignment_1(), "rule__ElementModification__ModificationAssignment_1");
					put(grammarAccess.getElementModificationAccess().getCommentAssignment_2(), "rule__ElementModification__CommentAssignment_2");
					put(grammarAccess.getElementReplaceableClauseAccess().getElementAssignment_1(), "rule__ElementReplaceableClause__ElementAssignment_1");
					put(grammarAccess.getElementReplaceableClauseAccess().getConstraintAssignment_2(), "rule__ElementReplaceableClause__ConstraintAssignment_2");
					put(grammarAccess.getElementComponentClauseAccess().getTypePrefixAssignment_0(), "rule__ElementComponentClause__TypePrefixAssignment_0");
					put(grammarAccess.getElementComponentClauseAccess().getTypeSpecifierAssignment_1(), "rule__ElementComponentClause__TypeSpecifierAssignment_1");
					put(grammarAccess.getElementComponentClauseAccess().getSubscriptsAssignment_3(), "rule__ElementComponentClause__SubscriptsAssignment_3");
					put(grammarAccess.getElementComponentClauseAccess().getModificationAssignment_4(), "rule__ElementComponentClause__ModificationAssignment_4");
					put(grammarAccess.getElementComponentClauseAccess().getCommentAssignment_5(), "rule__ElementComponentClause__CommentAssignment_5");
					put(grammarAccess.getEquation_rule_clauseAccess().getEquationRulesAssignment_1_0_0(), "rule__Equation_rule_clause__EquationRulesAssignment_1_0_0");
					put(grammarAccess.getEquation_rule_clauseAccess().getAnnotationsAssignment_1_1_0(), "rule__Equation_rule_clause__AnnotationsAssignment_1_1_0");
					put(grammarAccess.getAlgorithm_clauseAccess().getAlgorithmRulesAssignment_1_0_0(), "rule__Algorithm_clause__AlgorithmRulesAssignment_1_0_0");
					put(grammarAccess.getAlgorithm_clauseAccess().getAnnotationsAssignment_1_1_0(), "rule__Algorithm_clause__AnnotationsAssignment_1_1_0");
					put(grammarAccess.getEquation_ruleAccess().getCommentAssignment_1(), "rule__Equation_rule__CommentAssignment_1");
					put(grammarAccess.getAlgorithmAccess().getCommentAssignment_1(), "rule__Algorithm__CommentAssignment_1");
					put(grammarAccess.getConditional_equation_rule_eAccess().getThenEquationClausesAssignment_3_0(), "rule__Conditional_equation_rule_e__ThenEquationClausesAssignment_3_0");
					put(grammarAccess.getConditional_equation_rule_eAccess().getElseifClausesAssignment_4(), "rule__Conditional_equation_rule_e__ElseifClausesAssignment_4");
					put(grammarAccess.getConditional_equation_rule_eAccess().getElseEquationClausesAssignment_5_1_0(), "rule__Conditional_equation_rule_e__ElseEquationClausesAssignment_5_1_0");
					put(grammarAccess.getConditional_equation_rule_aAccess().getConditionAssignment_1(), "rule__Conditional_equation_rule_a__ConditionAssignment_1");
					put(grammarAccess.getConditional_equation_rule_aAccess().getThenAlgorithmClausesAssignment_3_0(), "rule__Conditional_equation_rule_a__ThenAlgorithmClausesAssignment_3_0");
					put(grammarAccess.getConditional_equation_rule_aAccess().getElseifClausesAssignment_4(), "rule__Conditional_equation_rule_a__ElseifClausesAssignment_4");
					put(grammarAccess.getConditional_equation_rule_aAccess().getElseAlgotithmClausesAssignment_5_1_0(), "rule__Conditional_equation_rule_a__ElseAlgotithmClausesAssignment_5_1_0");
					put(grammarAccess.getFor_clause_eAccess().getForIndicesAssignment_1(), "rule__For_clause_e__ForIndicesAssignment_1");
					put(grammarAccess.getFor_clause_eAccess().getEquationClausesAssignment_3_0(), "rule__For_clause_e__EquationClausesAssignment_3_0");
					put(grammarAccess.getFor_clause_aAccess().getForIndicesAssignment_1(), "rule__For_clause_a__ForIndicesAssignment_1");
					put(grammarAccess.getFor_clause_aAccess().getAlgorithmClausesAssignment_3_0(), "rule__For_clause_a__AlgorithmClausesAssignment_3_0");
					put(grammarAccess.getWhile_clauseAccess().getConditionAssignment_1(), "rule__While_clause__ConditionAssignment_1");
					put(grammarAccess.getWhile_clauseAccess().getAlgorithmClausesAssignment_3_0(), "rule__While_clause__AlgorithmClausesAssignment_3_0");
					put(grammarAccess.getWhen_clause_eAccess().getConditionAssignment_1(), "rule__When_clause_e__ConditionAssignment_1");
					put(grammarAccess.getWhen_clause_eAccess().getThenEquationClausesAssignment_3_0(), "rule__When_clause_e__ThenEquationClausesAssignment_3_0");
					put(grammarAccess.getWhen_clause_eAccess().getElseWhenClausesAssignment_4(), "rule__When_clause_e__ElseWhenClausesAssignment_4");
					put(grammarAccess.getElse_when_eAccess().getConditionAssignment_1(), "rule__Else_when_e__ConditionAssignment_1");
					put(grammarAccess.getElse_when_eAccess().getThenEquationClausesAssignment_3_0(), "rule__Else_when_e__ThenEquationClausesAssignment_3_0");
					put(grammarAccess.getWhen_clause_aAccess().getConditionAssignment_1(), "rule__When_clause_a__ConditionAssignment_1");
					put(grammarAccess.getWhen_clause_aAccess().getThenAlgorithmClausesAssignment_3_0(), "rule__When_clause_a__ThenAlgorithmClausesAssignment_3_0");
					put(grammarAccess.getWhen_clause_aAccess().getElseWhenClausesAssignment_4(), "rule__When_clause_a__ElseWhenClausesAssignment_4");
					put(grammarAccess.getElse_when_aAccess().getConditionAssignment_1(), "rule__Else_when_a__ConditionAssignment_1");
					put(grammarAccess.getElse_when_aAccess().getThenAlgorithmClausesAssignment_3_0(), "rule__Else_when_a__ThenAlgorithmClausesAssignment_3_0");
					put(grammarAccess.getEquation_rule_elseifAccess().getConditionAssignment_1(), "rule__Equation_rule_elseif__ConditionAssignment_1");
					put(grammarAccess.getEquation_rule_elseifAccess().getThenEquationClausesAssignment_3_0(), "rule__Equation_rule_elseif__ThenEquationClausesAssignment_3_0");
					put(grammarAccess.getAlgorithm_elseifAccess().getConditionAssignment_1(), "rule__Algorithm_elseif__ConditionAssignment_1");
					put(grammarAccess.getAlgorithm_elseifAccess().getThenAlgorithmClausesAssignment_3_0(), "rule__Algorithm_elseif__ThenAlgorithmClausesAssignment_3_0");
					put(grammarAccess.getCommentAccess().getStringAssignment_0(), "rule__Comment__StringAssignment_0");
					put(grammarAccess.getCommentAccess().getAnnotationAssignment_1(), "rule__Comment__AnnotationAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseParser typedParser = (org.modelica.xtext.contentassist.antlr.internal.InternalModelicaBaseParser) parser;
			typedParser.entryRuleStorageUnit();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ModelicaBaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModelicaBaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
