/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.algorithm.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.algorithm.services.AlgorithmsectionGrammarAccess;

import com.google.inject.Inject;

public class AlgorithmsectionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AlgorithmsectionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openmodelica.modelicaml.editor.xtext.algorithm.parser.antlr.internal.InternalAlgorithmsectionParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.algorithm.parser.antlr.internal.InternalAlgorithmsectionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "algorithm_clause";
	}
	
	public AlgorithmsectionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AlgorithmsectionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
