
/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.modification.ui.internal;

import java.util.HashMap;
import java.util.Map;

import org.apache.log4j.Logger;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

/**
 * Generated
 */
public class ModificationActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static ModificationActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("org.openmodelica.modelicaml.editor.xtext.modification.Modification", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("org.openmodelica.modelicaml.editor.xtext.modification.Modification")).with(getUiModule("org.openmodelica.modelicaml.editor.xtext.modification.Modification"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static ModificationActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("org.openmodelica.modelicaml.editor.xtext.modification.Modification".equals(grammar)) {
		  return new org.openmodelica.modelicaml.editor.xtext.modification.ModificationRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("org.openmodelica.modelicaml.editor.xtext.modification.Modification".equals(grammar)) {
		  return new org.openmodelica.modelicaml.editor.xtext.modification.ui.ModificationUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
