/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.valuebinding.ui.contentassist;

import org.openmodelica.modelicaml.editor.xtext.valuebinding.ui.contentassist.AbstractProviderProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProviderProposalProvider extends AbstractProviderProposalProvider {

}
