/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.modification.parser.antlr;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openmodelica.modelicaml.editor.xtext.modification.services.ModificationGrammarAccess;

import com.google.inject.Inject;

public class ModificationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ModificationGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, CharStream in) {
		TokenSource tokenSource = createLexer(in);
		XtextTokenStream tokenStream = createTokenStream(tokenSource);
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.openmodelica.modelicaml.editor.xtext.modification.parser.antlr.internal.InternalModificationParser parser = createParser(tokenStream);
		parser.setTokenTypeMap(getTokenDefProvider().getTokenDefMap());
		parser.setSyntaxErrorProvider(getSyntaxErrorProvider());
		parser.setUnorderedGroupHelper(getUnorderedGroupHelper().get());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	protected org.openmodelica.modelicaml.editor.xtext.modification.parser.antlr.internal.InternalModificationParser createParser(XtextTokenStream stream) {
		return new org.openmodelica.modelicaml.editor.xtext.modification.parser.antlr.internal.InternalModificationParser(stream, getElementFactory(), getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "modification_alternatives";
	}
	
	public ModificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
