/*
* generated by Xtext
*/
package org.modelica.xtext.contentassist;

import org.modelica.xtext.contentassist.AbstractModelicaBaseProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ModelicaBaseProposalProvider extends AbstractModelicaBaseProposalProvider {

}
