/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.algorithm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.openmodelica.modelicaml.editor.xtext.model.ui.autoedit.ModelicaMLAutoEditStrategyProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AlgorithmsectionUiModule extends org.openmodelica.modelicaml.editor.xtext.algorithm.ui.AbstractAlgorithmsectionUiModule {
	public AlgorithmsectionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return ModelicaMLAutoEditStrategyProvider.class;
	}
}
