/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.valuebinding.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MediatorUiModule extends org.openmodelica.modelicaml.editor.xtext.valuebinding.ui.AbstractMediatorUiModule {
	public MediatorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
