/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.valuebinding;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ClientRuntimeModule extends org.openmodelica.modelicaml.editor.xtext.valuebinding.AbstractClientRuntimeModule {

}
