/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.state.ui.contentassist;

import org.openmodelica.modelicaml.editor.xtext.state.ui.contentassist.AbstractStatetransitionguardexpressionProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StatetransitionguardexpressionProposalProvider extends AbstractStatetransitionguardexpressionProposalProvider {

}
