
/*
 * generated by Xtext
 */
 
package org.openmodelica.modelicaml.editor.xtext.algorithm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class AlgorithmsectionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.openmodelica.modelicaml.editor.xtext.algorithm.ui.internal.AlgorithmsectionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.openmodelica.modelicaml.editor.xtext.algorithm.ui.internal.AlgorithmsectionActivator.getInstance().getInjector("org.openmodelica.modelicaml.editor.xtext.algorithm.Algorithmsection");
	}
	
}
