
/*
 * generated by Xtext
 */
 
package org.openmodelica.modelicaml.editor.xtext.state.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class StatetransitionguardexpressionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.openmodelica.modelicaml.editor.xtext.state.ui.internal.StatetransitionguardexpressionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.openmodelica.modelicaml.editor.xtext.state.ui.internal.StatetransitionguardexpressionActivator.getInstance().getInjector("org.openmodelica.modelicaml.editor.xtext.state.Statetransitionguardexpression");
	}
	
}
