package org.modelica.mdt.debug.core.model;

/**
 * Listeners are notified of events occurring in a MDT program
 * being interpretted.
 * <p>
 * The events generated by the interpretor are:
 */
public interface IMDTEventListener {
	
	/**
	 * Notification the given event occurred in the target program
	 * being interpretted.
	 * 
	 * @param event the event
	 */
	public void handleEvent(String event);

}
