/*
 * generated by Xtext
 */
package org.openmodelica.modelicaml.editor.xtext.condition.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConditionalattributeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.openmodelica.modelicaml.editor.xtext.condition.ui.internal.ConditionalattributeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.openmodelica.modelicaml.editor.xtext.condition.ui.internal.ConditionalattributeActivator.getInstance().getInjector("org.openmodelica.modelicaml.editor.xtext.condition.Conditionalattribute");
	}
	
}
