/*
* generated by Xtext
*/
package org.openmodelica.modelicaml.editor.xtext.condition.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ConditionalattributeOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
